name: WakaTime Stats Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # SHA di checkout v3

      - name: Start WakaTime update
        run: echo "ðŸš€ Starting WakaTime update..."

      - name: Check WakaTime API Key
        run: |
          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
            echo "âŒ WakaTime API Key not found!"
            exit 1
          else
            echo "âœ… WakaTime API Key found"
          fi

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494  # SHA di v1.1.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: "->"
          IGNORED_LANGUAGES: "YAML JSON TOML"

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated WakaTime stats" || echo "No changes to commit"
          git push
